var listLocales = [
  ['0','Lava jato da Silva','Silva','Rápido e ainda conta com uma promoção.', '../imagens/jato.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam gravida erat ac arcu facilisis, quis scelerisque tortor molestie. Maecenas laoreet, dolor sed commodo tempor, neque mi lobortis massa, ac faucibus orci nibh in arcu. Mauris sed tincidunt lacus. Pellentesque mauris mauris, vulputate eu rhoncus eu, vulputate et nunc. Vivamus vestibulum feugiat quam, sed aliquam libero semper nec. Pellentesque malesuada, odio ut ultrices bibendum, tellus elit sollicitudin elit, in bibendum magna dolor ac nibh. Cras feugiat, nunc sed iaculis imperdiet, mauris lacus elementum nibh, et gravida elit tortor eu nibh. Curabitur eu lorem faucibus, bibendum odio sed, iaculis tortor. <br> Curabitur dictum ligula sit amet leo mollis, at finibus lacus feugiat. Ut leo lacus, faucibus ut nunc sed, euismod elementum magna. Nam nec arcu eu elit faucibus tempor id id metus. Etiam sit amet condimentum tortor. Aenean non massa a urna sodales vulputate vel a magna. Aenean fringilla sapien est, ullamcorper viverra tortor fringilla nec. Proin sit amet consequat eros. Suspendisse sed volutpat quam. Donec fermentum accumsan quam, eu malesuada odio gravida eu. Aliquam erat volutpat. Phasellus sodales, nisi a eleifend accumsan, lorem libero imperdiet dolor, et malesuada risus sapien at est.'],
  ['1','Mercado da Martha', 'Martha','Supermercado e com preços acessiveis', '../imagens/mercado.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam gravida erat ac arcu facilisis, quis scelerisque tortor molestie. Maecenas laoreet, dolor sed commodo tempor, neque mi lobortis massa, ac faucibus orci nibh in arcu. Mauris sed tincidunt lacus. Pellentesque mauris mauris, vulputate eu rhoncus eu, vulputate et nunc. Vivamus vestibulum feugiat quam, sed aliquam libero semper nec. Pellentesque malesuada, odio ut ultrices bibendum, tellus elit sollicitudin elit, in bibendum magna dolor ac nibh. Cras feugiat, nunc sed iaculis imperdiet, mauris lacus elementum nibh, et gravida elit tortor eu nibh. Curabitur eu lorem faucibus, bibendum odio sed, iaculis tortor. <br> Curabitur dictum ligula sit amet leo mollis, at finibus lacus feugiat. Ut leo lacus, faucibus ut nunc sed, euismod elementum magna. Nam nec arcu eu elit faucibus tempor id id metus. Etiam sit amet condimentum tortor. Aenean non massa a urna sodales vulputate vel a magna. Aenean fringilla sapien est, ullamcorper viverra tortor fringilla nec. Proin sit amet consequat eros. Suspendisse sed volutpat quam. Donec fermentum accumsan quam, eu malesuada odio gravida eu. Aliquam erat volutpat. Phasellus sodales, nisi a eleifend accumsan, lorem libero imperdiet dolor, et malesuada risus sapien at est.'],
  ['2','Lachoneto do Zé', 'ZÉ', 'Vendemos mini Pizzas','../imagens/lanchonete.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam gravida erat ac arcu facilisis, quis scelerisque tortor molestie. Maecenas laoreet, dolor sed commodo tempor, neque mi lobortis massa, ac faucibus orci nibh in arcu. Mauris sed tincidunt lacus. Pellentesque mauris mauris, vulputate eu rhoncus eu, vulputate et nunc. Vivamus vestibulum feugiat quam, sed aliquam libero semper nec. Pellentesque malesuada, odio ut ultrices bibendum, tellus elit sollicitudin elit, in bibendum magna dolor ac nibh. Cras feugiat, nunc sed iaculis imperdiet, mauris lacus elementum nibh, et gravida elit tortor eu nibh. Curabitur eu lorem faucibus, bibendum odio sed, iaculis tortor. <br> Curabitur dictum ligula sit amet leo mollis, at finibus lacus feugiat. Ut leo lacus, faucibus ut nunc sed, euismod elementum magna. Nam nec arcu eu elit faucibus tempor id id metus. Etiam sit amet condimentum tortor. Aenean non massa a urna sodales vulputate vel a magna. Aenean fringilla sapien est, ullamcorper viverra tortor fringilla nec. Proin sit amet consequat eros. Suspendisse sed volutpat quam. Donec fermentum accumsan quam, eu malesuada odio gravida eu. Aliquam erat volutpat. Phasellus sodales, nisi a eleifend accumsan, lorem libero imperdiet dolor, et malesuada risus sapien at est.'],
  ['3','Bar', 'Bardo','Bebidas e Drinks','../imagens/bar.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam gravida erat ac arcu facilisis, quis scelerisque tortor molestie. Maecenas laoreet, dolor sed commodo tempor, neque mi lobortis massa, ac faucibus orci nibh in arcu. Mauris sed tincidunt lacus. Pellentesque mauris mauris, vulputate eu rhoncus eu, vulputate et nunc. Vivamus vestibulum feugiat quam, sed aliquam libero semper nec. Pellentesque malesuada, odio ut ultrices bibendum, tellus elit sollicitudin elit, in bibendum magna dolor ac nibh. Cras feugiat, nunc sed iaculis imperdiet, mauris lacus elementum nibh, et gravida elit tortor eu nibh. Curabitur eu lorem faucibus, bibendum odio sed, iaculis tortor. <br> Curabitur dictum ligula sit amet leo mollis, at finibus lacus feugiat. Ut leo lacus, faucibus ut nunc sed, euismod elementum magna. Nam nec arcu eu elit faucibus tempor id id metus. Etiam sit amet condimentum tortor. Aenean non massa a urna sodales vulputate vel a magna. Aenean fringilla sapien est, ullamcorper viverra tortor fringilla nec. Proin sit amet consequat eros. Suspendisse sed volutpat quam. Donec fermentum accumsan quam, eu malesuada odio gravida eu. Aliquam erat volutpat. Phasellus sodales, nisi a eleifend accumsan, lorem libero imperdiet dolor, et malesuada risus sapien at est.']
]

window.onload = function(){
	var id = window.location.search.replace("?id=", "");
	var body = document.getElementById("bodyDetails");
	body.innerHTML = '<h1 class="Name">'+listLocales[id][1]+'</h1><img class="locationImage" src="'+listLocales[id][4]+'"><br><p class="owner">Dono: </p><p class="ownerName">'+listLocales[id][2]+'</p><p class="details"> '+listLocales[id][5]+'</p>';
};
